-- Fluxo oficial do Setor de Projetos (revisão 22/09/2026)
insert into etapa_modelos (codigo, ordem, fase, titulo, rotulo, setores, cliente_participa, entrada, saida, regra, opcional, aceite_formal, escopo) values
('01',1,1,'Fechamento do contrato','Contrato','{comercial}',false,'Negociação concluída','Dossiê do cliente','Dossiê incompleto volta ao Comercial; o fluxo não segue até a regularização',false,false,null),
('02',2,1,'Pasta e grupo do cliente','Pasta e grupo','{administrativo}',false,'Contrato fechado','Grupo oficial no WhatsApp','Acontece em paralelo ao envio do dossiê',false,false,null),
('03',3,1,'Apresentação e envio do briefing','Briefing','{projetos}',true,'Grupo de WhatsApp criado','Briefing preenchido','O fluxo pausa até o cliente preencher o briefing',false,false,null),
('04',4,1,'Agendamento da reunião de briefing','Agendamento','{administrativo}',true,'Briefing preenchido','Reunião de briefing marcada','Modalidade (presencial ou online) combinada no agendamento',false,false,null),
('05',5,1,'Reunião de briefing','Reunião','{projetos}',true,'Briefing e dossiê do Comercial','Ata da reunião assinada','Com informação suficiente, o projeto entra em desenvolvimento',false,false,null),
('06',6,2,'Levantamento e documentos','Levantamento','{projetos}',true,'Ata e briefing','Fotos e documentação','O estudo só começa com levantamento e documentos em mãos',false,false,null),
('07',7,2,'Estudo de planta baixa','Planta baixa','{projetos}',false,'Briefing, ata, fotos e documentos','Estudo preliminar em PDF','Ao finalizar, avisa no canal oficial para o Administrativo agendar',false,false,null),
('08',8,2,'Agendamento da apresentação da planta baixa','Agendamento','{administrativo}',true,'Aviso de finalização do Setor de Projetos','Reunião de apresentação marcada','Modalidade combinada no agendamento',false,false,null),
('09',9,2,'Apresentação da planta baixa','Apresentação','{projetos}',true,'Estudo preliminar em PDF','Aprovação do cliente','Até 3 rodadas de ajuste. Prazo mínimo: 7 dias (simples) e 15 (significativas)',false,false,null),
('10',10,2,'Aceite formal da planta baixa','Aceite','{projetos,administrativo}',true,'Cliente de acordo, sem novas alterações','Aceite assinado','Sem assinatura, nada avança',false,true,null),
('11',11,2,'Estudo de fachada','Fachada','{projetos}',false,'Aceite da planta baixa','Estudo de fachada em imagem','Ao finalizar, avisa no canal oficial para o Administrativo agendar',false,false,null),
('12',12,2,'Agendamento da apresentação da fachada','Agendamento','{administrativo}',true,'Aviso de finalização do Setor de Projetos','Reunião de apresentação marcada','Modalidade combinada no agendamento',false,false,null),
('13',13,2,'Apresentação da fachada','Apresentação','{projetos}',true,'Estudo de fachada em imagem','Aprovação do cliente','Até 3 rodadas de ajuste. Prazo mínimo: 7 dias (simples) e 15 (significativas)',false,false,null),
('14',14,2,'Aceite formal da fachada','Aceite','{projetos,administrativo}',true,'Cliente de acordo, sem novas alterações','Aceite assinado','Sem assinatura, nada avança',false,true,null),
('15',15,3,'Projeto arquitetônico','Arquitetônico','{projetos}',false,'Estudos aprovados','Projeto conferido','Outro profissional confere com o checklist antes de seguir',false,false,null),
('16',16,3,'Projeto legal','Legal','{projetos,terceiros}',false,'Projeto arquitetônico conferido','Projeto aprovado','Entregar ao cliente assim que a aprovação sair',true,false,'legal'),
('17',17,3,'Estudo de interiores','Estudo de interiores','{projetos,administrativo}',true,'Aceites do estudo preliminar','Aceite assinado','Mesmo ciclo de ajustes da planta baixa',true,true,'interiores'),
('18',18,3,'Detalhamento de interiores','Detalhamento','{projetos}',false,'Estudo de interiores aprovado','Detalhamento conferido','Análise interna antes da entrega',true,false,'interiores'),
('19',19,3,'Projetos complementares','Complementares','{projetos,terceiros}',false,'Arquitetônico ou estudo de interiores consolidado','Projetos complementares contratados','Antes, reunião de pontos técnicos com o cliente',true,false,'complementares'),
('20',20,4,'Conferência final','Conferência','{projetos}',false,'Etapas independentes concluídas','Pedido de agendamento','Cada etapa independente é entregue assim que concluída',false,false,null),
('21',21,4,'Agendamento da entrega','Agendamento','{administrativo}',true,'Solicitação do Setor de Projetos','Reunião de entrega marcada','Contato pelo canal oficial no WhatsApp',false,false,null),
('22',22,4,'Preparação da entrega','Preparação','{projetos}',false,'Reunião de entrega marcada','Materiais conferidos e separados','Pendrive apenas em projetos premium',false,false,null),
('23',23,4,'Reunião de entrega','Entrega','{projetos}',true,'Materiais conferidos e separados','Termo assinado e foto com o cliente','Documentação da Prefeitura só depois da aprovação',false,false,null),
('24',24,4,'Encerramento','Encerramento','{projetos}',false,'Entrega realizada','Projeto fora do Quadro de Projetos','Arquivar documentos e marcar como finalizado no Vobi',false,false,null),
('P1',25,5,'Pausa a pedido do cliente','A pedido','{projetos}',true,'Pedido do cliente','Termo assinado','O projeto fica parado até a retomada formal',false,false,null),
('P2',26,5,'Pausa por falta de retorno','Sem retorno','{administrativo}',false,'3 semanas sem resposta','Projeto pausado','Notificação por e-mail e aviso no WhatsApp',false,false,null),
('P3',27,5,'Retomada do projeto','Retomada','{projetos}',true,'Pedido de retorno','Aditivo assinado','Possível em até 180 dias de pausa',false,false,null),
('P4',28,5,'Prazo de pausa esgotado','Rescisão','{administrativo}',false,'181º dia de pausa','Contrato encerrado','Enviar o termo de rescisão por ausência de retomada',false,false,null)
on conflict (codigo) do nothing;
