-- Documentos exigidos em cada etapa (fluxo revisão 22/09/2026)
insert into documento_modelos (etapa_codigo, nome, padrao_arquivo, ordem) values
('01','Dossiê com as informações do cliente (app do Comercial)','DOS_CAXXXXXX_REVXX',1),
('02','Texto padrão para grupo de WhatsApp (cliente A para cima)',null,1),
('02','Texto padrão para grupo de WhatsApp (cliente B para baixo)',null,2),
('02','Texto padrão para grupo de WhatsApp (cliente + projetos)',null,3),
('03','Envio do briefing de projeto',null,1),
('03','Imagem briefing',null,2),
('03','Briefing respondido pelo cliente (Forms)','BRF_CAXXXXXX_REVXX',3),
('05','Ata de reunião de briefing','ATA_CAXXXXXX_BRF_DATA',1),
('06','Documentação do terreno ou imóvel',null,1),
('09','Ata de reunião da planta baixa','ATA_CAXXXXXX_ESTD_DATA',1),
('09','Projeto preliminar — planta baixa',null,2),
('10','Mensagem sobre os estudos',null,1),
('10','Aceite da planta baixa','ESTD_CAXXXXXX_REVIN',2),
('13','Ata de reunião da fachada','ATA_CAXXXXXX_FACH_DATA',1),
('13','Projeto preliminar — fachada',null,2),
('14','Mensagem sobre os estudos',null,1),
('14','Termo de aceite do estudo de fachada','ACT_CAXXXXXX_FACH_REVXX',2),
('15','Registro de conclusão de etapa para análise interna','RDCE_CAXXXXXX_ARQ_REVXX',1),
('15','Checklist do projeto arquitetônico','CHCK_CAXXXXXX_ARQ_REVXX',2),
('16','Registro de conclusão de etapa para análise interna','RDCE_CAXXXXXX_CON_REVXX',1),
('16','Checklist do projeto legal','CHCK_CAXXXXXX_CON_REVXX',2),
('16','Procuração (pessoa física ou jurídica)','PRC_CAXXXXXX_REVXX',3),
('16','Memorial descritivo','MMD_CAXXXXXX_REVXX',4),
('16','Termo de compromisso','TDC_CAXXXXXX_REVXX',5),
('16','Termo de veracidade (unifamiliar ou multifamiliar)','TDV_CAXXXXXX_REVXX',6),
('16','Protocolo de acompanhamento','PDAC_CAXXXXXX',7),
('16','RRT de projeto e/ou gestão',null,8),
('17','Briefing de interiores',null,1),
('17','Ata de reunião de interiores','ATA_CAXXXXXX_INTR_DATA',2),
('17','Mensagem sobre os estudos',null,3),
('17','Termo de aceite do estudo de projeto de interiores','ACT_CAXXXXXX_INTR_REVXX',4),
('19','Ata de reunião de pontos técnicos','ATA_CAXXXXXX_PTEC_DATA',1),
('19','Checklist dos complementares','CHCK_CAXXXXXX_COM_REVXX',2),
('22','Termo de retirada de documento','TDRD_CAXXXXXX_REVXX',1),
('22','Corpo do e-mail de entrega por e-mail',null,2),
('22','Diretrizes para retirada de documentos',null,3),
('23','Termo de retirada de documento assinado','TDRD_CAXXXXXX_REVXX',1),
('P1','Termo de solicitação de pausa de projeto','TDSP_CAXXXXXX_REVXX',1),
('P2','Notificação de pausa de projeto','NDPP_CAXXXXXX_REVXX',1),
('P3','Termo de retomada de projeto','TDRP_CAXXXXXX_REVXX',1),
('P3','Aditivo de retomada de projeto','ADRP_CAXXXXXX_REVXX',2),
('P4','Rescisão de contrato por ausência de retorno',null,1);
